service: laravel

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: us-east-1
  # Environment variables
  environment:
    APP_ENV: dev # Or use ${sls:stage} if you want the environment to match the stage
    APP_KEY: base64:P9gmpDugdag6FqTYqW4tfNxTvUnjESYsZPbeRw9v3LU=
    QUEUE_CONNECTION: sqs
    SQS_QUEUE: ${construct:jobs.queueUrl}
    MAIL_MAILER: smtp
    MAIL_HOST: sandbox.smtp.mailtrap.io
    MAIL_PORT: 2525
    MAIL_USERNAME: ${ssm:/laravel-dev/MAIL_USERNAME}
    MAIL_PASSWORD: ${ssm:/laravel-dev/MAIL_PASSWORD}
    MAIL_ENCRYPTION: tls
    MAIL_FROM_ADDRESS: "hello@example.com"

    DB_CONNECTION: mysql
    DB_HOST: laravel-db.c3skrpo4bdac.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_DATABASE: laravel-db
    DB_USERNAME: ${ssm:/laravel-dev/DB_USERNAME}
    DB_PASSWORD: ${ssm:/laravel-dev/DB_PASSWORD}

package:
  # Files and directories to exclude from deployment
  patterns:
    - "!node_modules/**"
    - "!public/storage"
    - "!resources/assets/**"
    - "!storage/**"
    - "!tests/**"
    - "!.env"

functions:
  # This function runs the Laravel website/API
  web:
    handler: public/index.php
    runtime: php-80-fpm
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: "*"

    vpc:
      securityGroupIds:
        - sg-0fe23e5839a37e0ba
      subnetIds:
        - subnet-08afab5fadd5aa497
        - subnet-0be03e24ebad8f7b0
        - subnet-078e3728da7ccddf5

  # This function lets us run artisan commands in Lambda
  artisan:
    handler: artisan
    runtime: php-80-console
    timeout: 720 # in seconds
    # Uncomment to also run the scheduler every minute
    events:
      - schedule:
          rate: rate(1 minute)
        #   input: '"schedule:run"'

    vpc:
      securityGroupIds:
        - sg-0fe23e5839a37e0ba
      subnetIds:
        - subnet-08afab5fadd5aa497
        - subnet-0be03e24ebad8f7b0
        - subnet-078e3728da7ccddf5

constructs:
  jobs:
    type: queue
    # This function runs Laravel Queues
    worker:
      handler: Bref\LaravelBridge\Queue\QueueHandler
      runtime: php-80
      timeout: 60 # second

plugins:
  - ./vendor/bref/bref
  - serverless-lift
